# Generated by Django 3.1.7 on 2021-05-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Irregular', 'Irregular')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptive_title', models.CharField(blank=True, max_length=50, null=True)),
                ('pre_requisite', models.CharField(blank=True, max_length=50, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('num_hours_lec', models.IntegerField(blank=True, null=True)),
                ('num_hours_lab', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.course')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('school_year', models.CharField(blank=True, max_length=100, null=True)),
                ('student_status', models.CharField(blank=True, choices=[('New', 'New'), ('Old', 'Old'), ('Transferee', 'Transferee'), ('Returnee', 'Returnee'), ('Shiftee', 'Shiftee'), ('Cross Enrollee', 'Cross Enrollee')], max_length=50, null=True)),
                ('block_section', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.course')),
                ('enrollment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollmentstatus')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.semester')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.yearlevel')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.yearlevel'),
        ),
        migrations.CreateModel(
            name='OfferedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=50, null=True)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.subject')),
            ],
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set1', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set2', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set3', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set4', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code5',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set5', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code6',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set6', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code7',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set7', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code8',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set8', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_code9',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_set9', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_codeA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_setA', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_codeB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_setB', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_codeC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_setC', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_codeD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_setD', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_codeE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_setE', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='mis_codeF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_code_setF', to='enrollment.offeredsubject'),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.semester'),
        ),
    ]
