# Generated by Django 3.1.7 on 2021-05-09 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20210509_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offeredsubject',
            old_name='selected',
            new_name='select',
        ),
        migrations.AddField(
            model_name='subjectform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enrollment.user'),
            preserve_default=False,
        ),
    ]
