# Generated by Django 3.1.7 on 2021-05-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_auto_20210509_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentstatus',
            name='identifier_irregular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentstatus',
            name='identifier_regular',
            field=models.BooleanField(default=False),
        ),
    ]
