# Generated by Django 3.1.7 on 2021-05-09 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_auto_20210509_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectform',
            old_name='user',
            new_name='student',
        ),
    ]
