# Generated by Django 3.1.7 on 2021-05-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_auto_20210509_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectform',
            name='student',
        ),
    ]
